### ISSUE TITLE
lzop is claiming that the lzo files that dpdkcap creates are corrupt

### ISSUE THREAD

**Issue by craiggarrett** [dpdkcap/dpdkcap#10]
I've been trying to have dpdkcap write out 25MB files, and when I try to use lzop to decompress them, only about 100KB (or less) of pcap is written to disk and then lzop errors out saying "lzop: output_01_000.pcap.lzo: lzop file corrupted". Data rate for the capture was relatively low, less than 10mbit/sec. Any ideas? 

I'm using the latest from dpdkcap's master branch (as of Sept 2016), with DPDK 16.11 on Ubuntu 16.04.1 (64-bit). Command line:
sudo -E ./build/dpdkcap --master-lcore 0 -w 00:08.0 -c 0x7 -n 1 -- --limit_file_size=25000000 -p 0x1

**Comment by groud** [comment]
Hello,
actually I think this problem happened to me before, but not anymore... Which version are you using ?

**Comment by craiggarrett** [comment]
I'm using a copy of master I downloaded a few days ago.

**Comment by groud** [comment]
Ok, Have you tried without the `limit_file_size` option ?
I actually do not have a lot of time to fix the problem, and missing a proper configuration to run tests. :/

**Comment by craiggarrett** [comment]
I have - here are all of the option combinations I've tried, and the issue is present with all of them.

`sudo -E ./build/dpdkcap --master-lcore 0 -w 00:08.0 -c 0x7 -n 1 -- -p 0x1 --limit_file_size=25000000`
`sudo -E ./build/dpdkcap --master-lcore 0 -w 00:08.0 -c 0x7 -n 1 -- -p 0x1 --rotate_seconds=100`
`sudo -E ./build/dpdkcap --master-lcore 0 -w 00:08.0 -c 0x7 -n 1 -- -p 0x1 -S`
`sudo -E ./build/dpdkcap --master-lcore 0 -w 00:08.0 -c 0x7 -n 1 -- -p 0x1`

**Comment by groud** [comment]
Ok, I might have found a problem. I pushed on my own repository (groud/dpdkcap), on the develop branch a new commit. This might fix the problem, could you check it out ?

**Comment by craiggarrett** [comment]
Still having the problem after you added the code to initialize minilzo. Not sure if this matters, but it seems as though lzop is able to extract a little more of the files (now it's in the 500k-1MB range instead of only ~100k).

**Comment by craiggarrett** [comment]
I'm going to investigate removing the lzo code, and write uncompressed (i.e. normal) pcap files to disk. Hopefully the greater I/O doesn't kill performance, because having uncompressed pcap files is actually preferred over lzo-compressed pcaps.

**Comment by Woutifier** [comment]
This problem is currently hard to debug for me since I do not have access to the right hardware. Removing the compression code should be fairly trivial. However, the maximum throughput will likely suffer, depending on your storage solution.

**Comment by groud** [comment]
Hello, 
Could you send us a screenshot of your statistics when your capture is done ?

**Comment by craiggarrett** [comment]
Here's the text output visible after I hit CTRL-C, and I've attached a screenshot of it while running.

Command Line:
`sudo -E ./build/dpdkcap --master-lcore 0 -w 00:08.0 -c 0x7 -n 1 -- -p 0x1 -S`

Output:
```
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 3 allocated
DPDKCAP: Port 0 MAC: 08 00 27 29 cd 14
DPDKCAP: Core 1 is writing using file template: output_%COREID.pcap.lzo.
DPDKCAP: Core 2 is capturing packets for port 0
DPDKCAP: Waiting for all cores to exit
DPDKCAP: Closed writing core 1
DPDKCAP: Closed capture core 2 (port 0)
```
Screenshot:
![dpdkcap_screenshot](https://cloud.githubusercontent.com/assets/4259557/21702220/94b9f926-d367-11e6-9b90-0e80fc15f382.png)

**Comment by groud** [comment]
According to the log, it seems that you are not loosing a lot of packets. (17.23k as input and 17.23k as output into the file)

Could you check how many packet are recorded into your capture file ?

**Comment by craiggarrett** [comment]
How should I check how many packets are in the capture file? The LZO file is corrupt, so I can't extract the complete pcap file. Is there something else I should look at?

**Comment by groud** [comment]
Well, last time I had this message (it happened on previous versions of dpdkcap), lzop (version 1.03) was still able to decompress the file. As the lzo is a block-based compression algorithm, it managed to decompress the file whole file but its end.

So maybe try with `lzop -d output_01.pcap.lzo`, then use Wireshark to check the file content (an # of packets written). 
If it does not work, and you if are allowed to share the file, maybe you could attach your lzo compressed capture file so I have a look to it.

**Comment by craiggarrett** [comment]
I didn't keep the lzo file from the run above with the screenshots, but I ran a second test: the on-screen statistics from dpdkcap said that it had written 15.85k packets, but after decompressing with lzop I opened the pcap file in Wireshark (which gave an error saying the file was cut short in the middle of a packet). Wireshark was able to read only 4424 packets from the pcap. I will see about creating a lzo file that I can post here (that might be possible next week).

**Comment by groud** [comment]
Wow... The difference is actually huge.
Anyway this will probably be really difficult to fix, as I cannot reproduce this behaviour with my configuration. I actually have to deal with 3Gb/s traffic, with 16 cores allowed to dpdkcap, which is a quite different situation... :/

I hope this is not a problem with the minilzo library, its code is actually unreadable...

Let us know for the file :)

**Comment by craiggarrett** [comment]
When you are working with 3Gb/s traffic, what bottlenecks have you run into? Ring buffer sizes between the capture cores and the writing cores? Disk I/O? I'm wondering just how fast dpdkcap can go. (if there's a better forum for me to post this question on, let me know)

**Comment by groud** [comment]
Very interesting question :)

In my situation, even with a 10Gb/s trafic on one port, I was able to handle the traffic with only one capture core. Adding more capture core was decreasing the performance.
Considering the writing core, you need a lot more, as the compression is an heavy process (I had 7 writing core for a single port). However, too many writing core could make the writing to disk a bottleneck, as you are writing into one different file for each writing core.

Concerning the disk I/O, we had 3 x 4To discs, with around 200Mb/s bandwidth each. The main bottleneck was here, even in Raid0 and capturing only 64bytes/packets this bandwidth was theoretically not sufficient in case full 10Gb/s bandwidth peak.

But well, we managed to capture during a week with only 0,0001% of loss (or somthing like that :) )

**Comment by groud** [comment]
And concerning the memory buffer, it only affects dpdkcap ability to handle trafic peaks. But usually it is filled so fast that the difference between two buffer sizes is not that important.

**Comment by craiggarrett** [comment]
Oh that's very interesting! (and promising!) Thank you!

**Comment by groud** [comment]
Hello again,

while having a look at the code, I found out two little bugs in core_capture.c and core_write.c.
I will fix this as soon as possible. It may solve the problem.

**Comment by groud** [comment]
Ok the problem seems fixed, could you checkout the develop branch an tell me if everything works better now ?

**Comment by craiggarrett** [comment]
The changes you've been making to the develop branch are great! But, it looks like the corrupt lzo files are still a problem for me on develop. I tried it with a file size limit, and with no file limit. When I use the new no-compression option, the pcap files appear to be intact.

Minor note: on the statistics screen with no-compression, the per core writing stats don't update the file size (it appears to remain at 0 bytes)

**Comment by groud** [comment]
(Concerning the minor note, it is now fixed :) )

**Comment by groud** [comment]
OK ! I managed to reproduce the bug.

I might have found something interesting, but I have to investigate.
I have no idea why, but it seem like replacing the line 37:
`block.len = __bswap_32(lzowrite_buffer->length);`
by
`block.out_length = __bswap_32(lzowrite_buffer->length);`

Seems to fix the problem...

I wish I had the documentation about how lzo files are created...

**Comment by groud** [comment]
EUREKA !

I know what is not working. I searched into the example files in the original source code.
When LZO is applied to a block, it might end up with a larger data block than the one we want to compress (uncompressible data). Thus in this situation the uncompressed data block should be written in place of the (not-really) compressed one !

This is not done into the current code, this must be the solution to ours problems. :)

**Comment by craiggarrett** [comment]
Gosh, I had no idea that using LZO was so complex! But thank you for adding the --no-compression option, that's what I needed anyway, as I have plenty of disk space and - I need the pcaps :)

If you commit a LZO change to develop and want me to test it, let me know.

**Comment by groud** [comment]
Well minilzo is not so complicated to use, but there is a lack of information about how the .lzo files are formatted. :)

Ok, when I am done with that I will tell you.

**Comment by groud** [comment]
Ok, the problem seems to be fixed know.
Could you try the last version on the develop branch ?

**Comment by craiggarrett** [comment]
Yes, it looks like it's working now! Nice work!

**Comment by groud** [comment]
Awesome, I close the issue.

**Comment by Woutifier** [comment]
@groud nice work! This bug has been around for a while :-)

**Comment by groud** [comment]
Thanks :grinning:
